// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO6NDTB8wQ3jzPFpnOEa08VOdJS4dP3pg',
    appId: '1:506178372311:android:d2a0de48663dd412f8e692',
    messagingSenderId: '506178372311',
    projectId: 'taskitty-c64b1',
    storageBucket: 'taskitty-c64b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6NDTB8wQ3jzPFpnOEa08VOdJS4dP3pg',
    appId: '1:506178372311:ios:ff4c7b513799d0d1f8e692',
    messagingSenderId: '506178372311',
    projectId: 'taskitty-c64b1',
    storageBucket: 'taskitty-c64b1.appspot.com',
    androidClientId:
        '506178372311-irrq1c1lfg2mstj0r4id2ftmdk4aa7n4.apps.googleusercontent.com',
    iosClientId:
        '506178372311-3klcr2gp3aggd1d5cp4hurml3h32gcb9.apps.googleusercontent.com',
    iosBundleId: 'com.twigcodes.taskittyFlutter',
  );
}
